
name: LeetCode Sync

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  LEETCODE_EMAIL: ${{ secrets.LEETCODE_EMAIL }}
  LEETCODE_PASSWORD: ${{ secrets.LEETCODE_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: LeetCode Sync
        uses: joshcai/leetcode-sync@v1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LEETCODE_EMAIL: ${{ secrets.LEETCODE_EMAIL }}
          LEETCODE_PASSWORD: ${{ secrets.LEETCODE_PASSWORD }}

